# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 7102

# ==============================================================================
# D a t e n b a n k
# ==============================================================================

db:
  type: postgres

  #host: localhost

  username: order_db_user
  password: GentleCorp09.04.2025
  populate: true

  schema: order_schema
  host: localhost
  database: order_db

  adminUsername: bn_keycloak
  passwordAdmin: "#3]O?4RGj)DE7Z!9SA5"

# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: localhost
  groupId: omnixys-order-service
  
# ==============================================================================
# K e y c l o a k
# ==============================================================================
# "Client Secret" muss durch die Umgebungsvariable CLIENT_SECRET gesetzt werden
keycloak:
  #schema: http
  host: localhost
  port: 18080
  realm: camunda-platform
  # siehe Keycloak Menuepunkt "Clients" > Tab "Clients list" > Spalte "Client ID"
  clientId: camunda-identity
  #tokenValidation: online

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./log
  pretty: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# J W T
# ==============================================================================
# 1d = 1 Tag, 1h = 1 Stunde, 1m = 1 Minute, 1s = 1 Sekunde
#jwt:
#  expiresIn: 1h
#  issuer: https://hka.de/JuergenZimmermann

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: localhost
  port: 5025
  log: false

# ==============================================================================
# T e s t s
# ==============================================================================
#test:
#  startDbServer: false
